--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skyss0fly/MultiVersionPM4
build-by-default: true
branches:
- main
projects:
  MultiVersionPM4:
    path: ""
    icon: "resources/icon.png"
...
